// ── GET /api/graph-html ───────────────────────────────────────────────────────
// Serves the interactive D3.js code graph visualization.
// Primary source: .code-review-graph/graph.html (generated by code-review-graph)
// Fallback: .toon/graphs/graph.html

import { promises as fs } from 'fs'
import path from 'path'
import { existsSync } from 'fs'

export async function GET(): Promise<Response> {
  try {
    // Try the primary code-review-graph output first
    let htmlPath = path.join(process.cwd(), '.code-review-graph', 'graph.html')
    if (!existsSync(htmlPath)) {
      // Fall back to the .toon/graphs copy
      htmlPath = path.join(process.cwd(), '.toon', 'graphs', 'graph.html')
    }

    const html = await fs.readFile(htmlPath, 'utf-8')
    return new Response(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    })
  } catch {
    return new Response(
      '<h1>Graph not found</h1><p>Run <code>npm run graphify:build</code> to generate the visualization.</p>',
      {
        status: 404,
        headers: { 'Content-Type': 'text/html' },
      }
    )
  }
}
