import type { Config } from 'tailwindcss'

// Design tokens ported from the YVON dashboard (Material Design 3 dark theme).
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#14305a',
        'secondary-fixed': '#d7e2ff',
        'on-tertiary': '#562000',
        error: '#ffb4ab',
        primary: '#abc7ff',
        'primary-fixed-dim': '#abc7ff',
        'on-tertiary-fixed': '#341000',
        'inverse-surface': '#e2e2e2',
        'tertiary-fixed': '#ffdbcb',
        'secondary-container': '#2e4772',
        'on-error-container': '#ffdad6',
        'primary-container': '#0071e3',
        'error-container': '#93000a',
        'surface-container': '#1f1f1f',
        'on-surface-variant': '#c1c6d6',
        'on-surface': '#e2e2e2',
        outline: '#8b919f',
        'on-secondary-fixed': '#001b3f',
        'on-secondary-container': '#9db5e7',
        'on-primary': '#002f66',
        background: '#0e0e0e',
        'on-primary-fixed': '#001b3f',
        'primary-fixed': '#d7e2ff',
        'on-tertiary-container': '#fffaf9',
        'on-primary-container': '#fcfbff',
        'inverse-on-surface': '#303030',
        'surface-variant': '#353535',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#ffb693',
        'surface-tint': '#abc7ff',
        secondary: '#aec7f9',
        'surface-container-lowest': '#0e0e0e',
        tertiary: '#ffb693',
        surface: '#131313',
        'on-secondary-fixed-variant': '#2e4772',
        'on-primary-fixed-variant': '#00458f',
        'on-background': '#e2e2e2',
        'surface-dim': '#131313',
        'inverse-primary': '#005cbb',
        'surface-bright': '#393939',
        'tertiary-container': '#c25100',
        'surface-container-low': '#1b1b1b',
        'outline-variant': '#414753',
        'secondary-fixed-dim': '#aec7f9',
        'surface-container-highest': '#353535',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#7a3000',
        // workspace accent (driven by CSS var so it can re-theme per workspace)
        accent: 'var(--ws-accent)',
        'accent-soft': 'var(--ws-accent-soft)',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1.25rem',
        xl: '2rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['SF Pro Display', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
