/**
 * curator.mjs — YVON self-improvement curator
 * Inspired by Hermes Agent curator system.
 *
 * Scans agent memories, consolidates duplicates, archives stale entries,
 * and generates a curator report. Run via: npm run curator
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const MEMORY_DIR = '/Users/novysingh/.claude/projects/-Users-novysingh-StudioProjects-YVON2-0/memory';
const ARCHIVE_DIR = join(MEMORY_DIR, 'archived');
const REPORT_DIR = join(ROOT, 'logs', 'curator');

const STALE_AFTER_DAYS = 30;
const ARCHIVE_AFTER_DAYS = 90;

function daysSince(dateStr) {
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return 0;
  return (Date.now() - d.getTime()) / 86400000;
}

function loadMemoryIndex() {
  const path = join(MEMORY_DIR, 'MEMORY.md');
  if (!existsSync(path)) return { lines: [], entries: [] };
  const content = readFileSync(path, 'utf-8');
  const lines = content.split('\n').filter(Boolean);
  const entries = [];
  for (const line of lines) {
    const match = line.match(/\[(.*?)\]\((.*?)\)/);
    if (match) entries.push({ name: match[1], file: match[2], line });
  }
  return { lines, entries };
}

function analyzeMemoryFiles() {
  const files = readdirSync(MEMORY_DIR).filter(f => f.endsWith('.md') && f !== 'MEMORY.md');
  const results = [];

  for (const file of files) {
    const path = join(MEMORY_DIR, file);
    const content = readFileSync(path, 'utf-8');
    const stats = { file, path, size: content.length, lines: content.split('\n').length, hasName: false, hasDesc: false, hasType: false, stale: false, age: 0 };

    // Check frontmatter
    if (content.startsWith('---')) {
      const fm = content.split('---')[1] || '';
      stats.hasName = fm.includes('name:');
      stats.hasDesc = fm.includes('description:');
      stats.hasType = fm.includes('metadata:') && fm.includes('type:');
    }

    // Check if stale based on content patterns (no hard dates typically)
    if (content.includes('(stale)') || content.includes('STALE')) stats.stale = true;

    results.push(stats);
  }

  return results;
}

function generateReport(analysis, index) {
  const now = new Date().toISOString().split('T')[0];
  const report = [
    `# Curator Report — ${now}`,
    '',
    '## Memory Index',
    `Total entries: ${index.entries.length}`,
    `Memory files: ${analysis.length}`,
    '',
    '## Analysis',
    ...analysis.map(a => {
      const flags = [];
      if (!a.hasName) flags.push('missing name');
      if (!a.hasDesc) flags.push('missing description');
      if (!a.hasType) flags.push('missing type');
      if (a.stale) flags.push('**STALE**');
      return `- ${a.file} (${a.lines} lines)${flags.length ? ' — ' + flags.join(', ') : ''}`;
    }),
    '',
    '## Recommendations',
  ];

  // Find entries missing frontmatter
  const missing = analysis.filter(a => !a.hasName || !a.hasDesc || !a.hasType);
  if (missing.length) {
    report.push('### Needs frontmatter fixes');
    missing.forEach(m => report.push(`- ${m.file}`));
  }

  // Check for potential duplicates (similar names)
  const names = index.entries.map(e => e.name.toLowerCase().replace(/[-_]/g, ' '));
  const duplicates = [];
  for (let i = 0; i < names.length; i++) {
    for (let j = i + 1; j < names.length; j++) {
      if (names[i] === names[j] || names[i].includes(names[j]) || names[j].includes(names[i])) {
        duplicates.push([index.entries[i], index.entries[j]]);
      }
    }
  }
  if (duplicates.length) {
    report.push('', '### Potential duplicates');
    duplicates.forEach(([a, b]) => report.push(`- "${a.name}" ↔ "${b.name}" (${a.file}, ${b.file})`));
  }

  report.push('', '---', '', `_Generated by YVON Curator on ${now}_`);
  return report.join('\n');
}

function runCurator() {
  // Ensure archive dir exists
  if (!existsSync(ARCHIVE_DIR)) mkdirSync(ARCHIVE_DIR, { recursive: true });
  if (!existsSync(REPORT_DIR)) mkdirSync(REPORT_DIR, { recursive: true });

  const index = loadMemoryIndex();
  const analysis = analyzeMemoryFiles();
  const report = generateReport(analysis, index);

  const reportPath = join(REPORT_DIR, `curator-${new Date().toISOString().split('T')[0]}.md`);
  writeFileSync(reportPath, report, 'utf-8');

  console.log(`\n  Curator report written to: ${reportPath}`);
  console.log(`  Memory entries: ${index.entries.length}`);
  console.log(`  Files analyzed: ${analysis.length}`);

  const flags = analysis.filter(a => !a.hasName || !a.hasDesc || !a.hasType);
  if (flags.length) console.log(`  Needs frontmatter fixes: ${flags.length}`);

  // Check for duplicates
  const names = index.entries.map(e => e.name.toLowerCase().replace(/[-_]/g, ' '));
  let dupCount = 0;
  for (let i = 0; i < names.length; i++) {
    for (let j = i + 1; j < names.length; j++) {
      if (names[i] === names[j] || names[i].includes(names[j]) || names[j].includes(names[i])) dupCount++;
    }
  }
  if (dupCount) console.log(`  Potential duplicates: ${dupCount}`);

  console.log();
}

runCurator();
