/**
 * insights.mjs — YVON agent insights generator
 * Inspired by Hermes Agent InsightsEngine.
 *
 * Analyzes recent activity, tool usage, patterns and generates an insights report.
 * Run via: npm run insights
 */

import { execSync } from 'child_process';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const REPORT_DIR = join(ROOT, 'logs', 'insights');
const MEMORY_DIR = '/Users/novysingh/.claude/projects/-Users-novysingh-StudioProjects-YVON2-0/memory';

function run(cmd, opts = {}) {
  try { return execSync(cmd, { encoding: 'utf-8', cwd: ROOT, ...opts }); }
  catch (e) { return e.stdout || ''; }
}

function analyzeGitActivity(days = 7) {
  const since = new Date(Date.now() - days * 86400000).toISOString().split('T')[0];
  const log = run(`git log --since="${since}" --oneline --no-merges 2>/dev/null`);
  const commits = log.split('\n').filter(Boolean);

  const files = run(`git diff --name-only $(git rev-list --max-parents=0 HEAD)..HEAD 2>/dev/null`).split('\n').filter(Boolean);

  return { commits: commits.length, files: files.length, fileList: files.slice(0, 20) };
}

function analyzeMemoryUsage() {
  if (!existsSync(MEMORY_DIR)) return { files: 0, entries: 0, files: [] };
  const files = require('fs').readdirSync(MEMORY_DIR).filter(f => f.endsWith('.md'));
  const entries = files.filter(f => f !== 'MEMORY.md').length;
  return { files: files.length, entries, names: files };
}

function generateInsightsReport(days = 7) {
  const git = analyzeGitActivity(days);
  const memory = analyzeMemoryUsage();

  if (!existsSync(REPORT_DIR)) mkdirSync(REPORT_DIR, { recursive: true });

  const report = [
    `# Insights Report — Last ${days} Days`,
    '',
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Activity',
    `- Commits: ${git.commits}`,
    `- Files touched: ${git.files}`,
    ...(git.fileList.length ? ['', '### Files changed', ...git.fileList.map(f => `- \`${f}\``)] : []),
    '',
    '## Memory',
    `- Memory files: ${memory.files}`,
    `- Active entries: ${memory.entries}`,
    ...(memory.names?.length ? ['', '### Memory files', ...memory.names.map(n => `- ${n}`)] : []),
    '',
    '---',
    '',
    '## Observations',
    git.commits === 0 ? '- No recent activity in this period.' : `- ${git.commits} commits in the last ${days} days.`,
    git.files > 20 ? '- High file churn — consider if refactoring is needed.' : '- Normal file change volume.',
    memory.entries > 20 ? '- Large memory store — consider running curator to consolidate.' : '- Memory store is manageable.',
    '',
    `_Generated by YVON Insights on ${new Date().toISOString()} _`,
  ].join('\n');

  const reportPath = join(REPORT_DIR, `insights-${new Date().toISOString().split('T')[0]}.md`);
  writeFileSync(reportPath, report, 'utf-8');
  console.log(`\n  Insights report: ${reportPath}`);
  console.log();
}

generateInsightsReport(parseInt(process.argv[2]) || 7);
